name: GitHub Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          user: Jayant-Kishore # <--- IMPORTANT: Make sure this is your exact GitHub username!

          # GITHUB_TOKEN is automatically provided by GitHub Actions
          # It has permissions to read private repos within your account
          token: ${{ secrets.GITHUB_TOKEN }}

          # Output file for the main stats card
          output_branch: master # Or 'main' if your default branch is main
          output_path: metrics.svg # This will be the name of the generated SVG file

          # Basic configuration
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Enable plugin to count private contributions
          plugin_traffic: yes
          plugin_traffic_recent_days: 14 # Can be adjusted
          plugin_traffic_type: commits, views, clones # Display types

          # Display all available trophies (achievements)
          plugin_achievements: yes
          plugin_achievements_threshold: C # You can adjust this (A, B, C, D, S, X)
          plugin_achievements_secrets: yes # Required to scan for achievement secrets (e.g., specific badges)

          # Themes (optional, you can explore more on lowlighter/metrics repo)
          config_timezone: Asia/Kolkata # Important for accurate daily activity, replace with your timezone
          config_order: base.header, isocalendar, traffic, achievements, repositories, base.activity, base.community, base.metadata
          # You can add more plugins and configurations here based on their docs
          # For example, to show specific languages:
          # plugin_languages: yes
          # plugin_languages_ignored: javascript, html, css
          # plugin_languages_limit: 8
          # plugin_languages_sections: most-used, recently-used
